version: "3.9"

networks:
  default:
    external: true
    name: elastic


services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=nmc_bookstore
    # networks:
    #   default:
    #     ipv4_address: 172.18.0.2
    ports:
      - "5432:5432"
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:123456@postgres:5432/nmc_bookstore?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["sh", "/app/wait-for", "postgres:5432", "--", "/app/main"]