version: "3.9"


networks:
  default:
    external: true
    name: nmc_bookstore
    
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 
      always
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=${DB_SOURCE}
    entrypoint: ["/app/main"]
